### ISSUE TITLE
Add to pypi

### ISSUE THREAD

**Issue by stantond** [avaldebe/PyPMS#10]
So that it can be more easily discovered and then installed with PIP

**Comment by avaldebe** [comment]
Yes, I'll make sure the next release ends up on PPI

**Comment by avaldebe** [comment]
# TODO

- [ ] close #3
- [ ] cose #4
- [ ] merge #5
- [ ] tag 0.2.0 and create release (trigger zenodo DOI)
- [ ] publish on pypi (with new package/cli name)
