### ISSUE TITLE
SDS198 not working

### ISSUE THREAD

**Issue by ifiwaspresident** [avaldebe/PyPMS#11]
Dear Alvaro,

I tried to connect a Nova SDS198 to my Rpi but it does not work. I also testet a Nova SDS011 and it works just fine!
Can you help me to bug fix?

Here is the dump from the debug mode:

```
pi@raspberrypi:~/Desktop/PyPMS $ /home/pi/.local/bin/pms -m SDS198 -s /dev/ttyUSB0 -i 10  --debug serial
DEBUG:pms:buffer length: 20
DEBUG:pms:Guess SDS198 from buffer contents
DEBUG:pms:message hex: aacf00000000e905eeab
DEBUG:pms:message header: b'\xaa\xcf'
DEBUG:pms:message hex: aacf00000000e905eeab
DEBUG:pms:message header: b'\xaa\xcf'
DEBUG:pms:message hex: aacf00000000e905eeab
DEBUG:pms:message header: b'\xaa\xcf'
DEBUG:pms:message hex: aacf00000000e905eeab
DEBUG:pms:message header: b'\xaa\xcf'
DEBUG:pms:message hex: aacf00000000e905eeab
DEBUG:pms:message header: b'\xaa\xcf'

```

Cheers, Alex

**Comment by ifiwaspresident** [comment]
I found the problem. the sds198 and sds011 have differen header.

in SDS01x.py I changed line 72 so it will accept if the head is something like "\xaa\x**":
`        if msg.header[-2] != header[-2]:
            raise WrongMessageFormat(f"message header: {msg.header!r}")
`

**Comment by avaldebe** [comment]
> I found the problem. the sds198 and sds011 have differen header.

Yes, I do not have a `SDS198` to test so I coded it from the datasheet and missed that detail.

> in SDS01x.py I changed line 72 so it will accept if the head is something like "\xaa\x**":
> 
> ```python
>         if msg.header[-2] != header[-2]:
>             raise WrongMessageFormat(f"message header: {msg.header!r}")
> ```

It is a neat hack. I'll fix `SDS198` header (SDS198.py) as follows

```pytython
commands = SDS01x.commands._replace(
    passive_read=base.Cmd(
        b"\xAA\xB4\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xFF\xFF\x02\xAB",
        b"\xAA\xCF",
        10,
    )
)
```

Also, I tried to use one of your debug messages and I can see that the message is empty (PM100 is 0 ug/m3).
I find this very strange. Can you give me different messages to test?

**Comment by avaldebe** [comment]
@ifiwaspresident 

Were you able to test the fix?
Can I close this issue?

**Comment by ifiwaspresident** [comment]
I hadn't had a chance of testing because of vacation time. But I will try it next week when I'm back. Thanks!

**Comment by ifiwaspresident** [comment]
@avaldebe 
Thank you for the fix. I think it works fine.

here are some print outs:

2020-09-09 14:58:30: PM100 16.0 ug/m3 
DEBUG:pms:message hex: aacf0e001000e9050cab 
DEBUG:pms:message payload: (14, 16, 1513) 
2020-09-09 14:58:40: PM100 16.0 ug/m3 
DEBUG:pms:message hex: aacf0e001300e9050fab 
DEBUG:pms:message payload: (14, 19, 1513)
2020-09-09 14:58:50: PM100 19.0 ug/m3
DEBUG:pms:message hex: aacf0c001600e90510ab
DEBUG:pms:message payload: (12, 22, 1513)
2020-09-09 14:59:00: PM100 22.0 ug/m3
DEBUG:pms:message hex: aacf0c001a00e90514ab
DEBUG:pms:message payload: (12, 26, 1513)
2020-09-09 14:59:10: PM100 26.0 ug/m3
DEBUG:pms:message hex: aacf0b001400e9050dab
DEBUG:pms:message payload: (11, 20, 1513)
2020-09-09 14:59:20: PM100 20.0 ug/m3
DEBUG:pms:message hex: aac506010100e905f6ab
DEBUG:pms:message payload: (262, 1, 1513)
2020-09-09 14:59:30: PM100 1.0 ug/m3
