### ISSUE TITLE
pip3 module not found

### ISSUE THREAD

**Issue by pczolee** [avaldebe/PyPMS#18]
Hello.

I trying to install this module on my raspberry pi Debian 9.11, Python 3.5.3, but it is not found :( .

# pip3 install pypms
Collecting pypms
  Could not find a version that satisfies the requirement pypms (from versions: )
No matching distribution found for pypms

Can you help me how can i install and use it in this system?

Thanks

**Comment by avaldebe** [comment]
You need python 3.6 or newer. You can use [pyenv](https://github.com/pyenv/pyenv) to install current version of Python.

**Comment by pczolee** [comment]
Thanks for the answer. Unfortunately bad news, but I give a try to pyenv.
