### ISSUE TITLE
logging.basicConfig() conflicts with use as a library

### ISSUE THREAD

**Issue by benthorner** [avaldebe/PyPMS#27]
Great codebase - really helpful to have all this knowledge in one place!

I've started using `pms` as a library in my own project. A small problem I encountered is [this line](https://github.com/avaldebe/PyPMS/blob/2ac146bab62e75a7c8d39a1a72810f63db4dd972/src/pms/__init__.py#L4), which means I have to use `force=True` when I call [`logging.basicConfig`](https://docs.python.org/3/library/logging.html#logging.basicConfig) in order for it to pick up my preferred settings.

Would it be possible to move that line to the `pms.cli` module? I reckon that should preserve the existing behaviour for CLI users. Happy to make a PR for it but thought it would be best to ask first.

**Comment by avaldebe** [comment]
> Would it be possible to move that line to the `pms.cli` module? I reckon that should preserve the existing behaviour for CLI users.
> Happy to make a PR for it but thought it would be best to ask first.

Sure, PRs are most welcomed
