### ISSUE TITLE
pms: Command not found

### ISSUE THREAD

**Issue by BismuthOxide7** [avaldebe/PyPMS#38]
Trying to use pypms on my rpi zero 2w
Installed using most recent version of pip.
The `pms --help` and `pms serial ` commands do not work - they give the error `bash: pms: command not found`
I am not sure what I am missing - tried the commands as root and still do not work.
I am unfamiliar with python and raspberry pi in general so any help is appreciated, I am hoping to be able to read PM measurements from my Sensiron SPS30.

**Comment by avaldebe** [comment]
How did you installed this package? Did you use any of the methods described on the [docs]?
Or did you use a different install method, such as `conda install` or `apt install`?
Also, did you run any of these methods under `sudo`?


[docs]: https://avaldebe.github.io/PyPMS/#installation

**Comment by BismuthOxide7** [comment]
The program was installed using `python3 -m pip install pypms` as the root user. I followed the instructions of the docs.

**Comment by avaldebe** [comment]
As far as I understand the `root` user has no `$HOME`, so I do not know if the package will be installed correctly.
Can you install it under your default user (not `root`), following the `pipx` installation instructions (also in the docs)?

**Comment by BismuthOxide7** [comment]
Installed using 'pipx' instruction through docs, seems to be working now!
